version: '2.4'

services:
  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - '8002:8000'
    volumes:
      - './project:/usr/src/app:delegated'
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - ENVIRONMENT=dev
      - TESTING=0
